[package]
name = "alias"
version = "0.0.1"
authors = ["Trevor <hello.tjtc.near>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0"
near-contract-standards = "3.2.0"
